from . import patient
from . import Appointments
from . import doctor
from . import bill
from . import commands
from . import table
from . import inherit_sale_order
from . import account_move_custom
from . import create_invoice_inherit
from . import custom_invoice_lines
from . import hr_teacher